// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_sas_ct_assault_benjamin_");
	self attach("head_sas_ct_assault_benjamin_nomask_", "", true);
	self.voice = "british";
}

precache()
{
	precacheModel("body_sas_ct_assault_benjamin_");
	precacheModel("head_sas_ct_assault_benjamin_nomask_");
}
