// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_forest_tf141_assault_b");
	self attach("head_tf141_forest_b", "", true);
	self.voice = "british";
}

precache()
{
	precacheModel("body_forest_tf141_assault_b");
	precacheModel("head_tf141_forest_b");
}
