// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_tf141_assault_a");
	self attach("head_tf141_forest_a", "", true);
	self.voice = "british";
}

precache()
{
	precacheModel("body_tf141_assault_a");
	precacheModel("head_tf141_forest_a");
}
