// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_sas_ct_assault_charles_");
	self attach("head_sas_woodland_gaz_", "", true);
	self.voice = "british";
}

precache()
{
	precacheModel("body_sas_ct_assault_charles_");
	precacheModel("head_sas_woodland_gaz_");
}
