// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_forest_tf141_assault_a");
	if( level.script == "blackout" ){
		self attach("head_sas_woodland_price_nvg", "", true);
	}
	else{
		self attach("head_hero_price_desert_", "", true);
	}
	
	self.voice = "british";
}

precache()
{
	precacheModel("body_forest_tf141_assault_a");
	if( level.script == "blackout" ){
		precacheModel("head_sas_woodland_price_nvg");
	}
	else{
		precacheModel("head_hero_price_desert_");
	}
}
