// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_forest_tf141_assault_a_griggs");
	self attach("head_force_assault_mark_", "", true);
	self.voice = "british";
}

precache()
{
	precacheModel("body_forest_tf141_assault_a_griggs");
	precacheModel("head_force_assault_mark_");
}
