// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_forest_tf141_shotgun");
	self attach("head_tf141_forest_c", "", true);
	self.voice = "british";
}

precache()
{
	precacheModel("body_forest_tf141_shotgun");
	precacheModel("head_tf141_forest_c");
}
