// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_sas_ct_assault_price_");
	self attach("head_sas_ct_assault_price_mask_down_", "", true);
	self.voice = "british";
}

precache()
{
	precacheModel("body_sas_ct_assault_price_");
	precacheModel("head_sas_ct_assault_price_mask_down_");
}
