// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_sas_ct_assault_mitchel");
	self attach("head_sas_ct_assault_mitchel", "", true);
	self.voice = "british";
}

precache()
{
	precacheModel("body_sas_ct_assault_mitchel");
	precacheModel("head_sas_ct_assault_mitchel");
}
