// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_sas_ct_assault_neal");
	self attach("head_sas_ct_assault_neal_nomask", "", true);
	self.voice = "british";
}

precache()
{
	precacheModel("body_sas_ct_assault_neal");
	precacheModel("head_sas_ct_assault_neal_nomask");
}
