// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_force_mark_woodland_");
	self attach("head_force_assault_mark_", "", true);
	self.voice = "british";
}

precache()
{
	precacheModel("body_force_mark_woodland_");
	precacheModel("head_force_assault_mark_");
}
