// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_forest_tf141_assault_a");
	self attach("head_sas_woodland_price_", "", true);
	self.voice = "british";
}

precache()
{
	precacheModel("body_forest_tf141_assault_a");
	precacheModel("head_sas_woodland_price_");
}
