// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_complete_sp_usmc_force_mark_");
	self.voice = "british";
}

precache()
{
	precacheModel("body_complete_sp_usmc_force_mark_");
}
