// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_sas_ct_assault_neal_");
	self attach("head_sas_ct_assault_neal__nomask", "", true);
	self.voice = "british";
}

precache()
{
	precacheModel("body_sas_ct_assault_neal_");
	precacheModel("head_sas_ct_assault_neal__nomask");
}
