// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_sas_ct_assault_william_");
	self attach("head_sas_ct_assault_william_", "", true);
	self.voice = "british";
}

precache()
{
	precacheModel("body_sas_ct_assault_william_");
	precacheModel("head_sas_ct_assault_william_");
}
