// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_sas_ct_assault_william");
	self attach("head_sas_ct_assault_william", "", true);
	self.voice = "british";
}

precache()
{
	precacheModel("body_sas_ct_assault_william");
	precacheModel("head_sas_ct_assault_william");
}
